name: Main CI/CD pipeline

on:
  release:
    tags:
      - 'main*'
    types:
      - published
env:
  AZURE_WEBAPP_NAME: main App 
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NUGET_VERSION: 5.10.0

jobs:
  first:
    if: github.ref == 'refs/tags/*-main'
    runs-on: windows-latest
    steps:
    - name: checkout repo

      run: |
        echo 'Comlpeted first jods for deployment in main branch vesion'${{ github.ref }}

  second:
    runs-on: windows-latest
    steps:
      - name: second job
        run: |
         echo 'Second Completed jods for deployment in main branch - github.ref: ' ${{ github.ref }}