name: Main CI/CD pipeline

on:
  release:
    tags:
      - 'main*'
    types:
      - published
env:
  AZURE_WEBAPP_NAME: main App 
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NUGET_VERSION: 5.10.0

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest

    steps:
    - name: checkout repo

      run: |
        echo 'Comlpeted jods for deployment in main branch'