name: Master CI/CD pipeline

on:
  release:
    branches:
      - master
    types:
      - published
env:
  AZURE_WEBAPP_NAME: master App 
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NUGET_VERSION: 5.10.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2