name: Master CI/CD pipeline

on:
  release:
    types:
      - published
env:
  AZURE_WEBAPP_NAME: master App 
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NUGET_VERSION: 5.10.0

jobs:
  first:
    name: Setup and Checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout repo

      run: |
        cat index.txt
        echo 'Comlpeted first jods for deployment in master branch vesion'${{ github.ref }}

  second:
    runs-on: windows-latest
    steps:
      - name: second job
        run: |
         echo 'Second Completed jods for deployment in master branch - github.ref: ' ${{ github.ref }}